import { useCallback, useEffect, useMemo, useState } from "react"
import { ExternalLink, Search, Trash2 } from "lucide-react"
import { useAuth } from "@/context/auth-context"

type Preview = { url:string; title:string; authorName:string; artworkUrl?:string|null; providerUrl?:string }
type Artist = { id:number; profile_url:string; name:string; artwork_url?:string; description?:string; active:boolean; sort_order:number }
type Item = { id:number; scope:"lowradio"|"partner"; artist_id?:number; kind:"track"|"playlist"; soundcloud_url:string; title:string; author_name?:string; artwork_url?:string; active:boolean; sort_order:number }
type Data = { settings?:{lowradio_profile_url?:string;lowradio_tracks_url?:string}; artists:Artist[]; items:Item[] }
const DEFAULT_LOWRADIO_TRACKS_URL = "https://soundcloud.com/lowradiolive/tracks"

function PreviewCard({ data }: { data:Preview }) { return <div className="sc-link-preview">{data.artworkUrl?<img src={data.artworkUrl} alt=""/>:<span>SC</span>}<div><small>DOĞRULANMIŞ SOUNDCLOUD</small><strong>{data.title}</strong><em>{data.authorName}</em></div><ExternalLink/></div> }

function useUrlPreview(url:string, fetcher:(url:string)=>Promise<Response>, expected?:"profile") {
  const [preview,setPreview]=useState<Preview|null>(null), [error,setError]=useState(""), [checking,setChecking]=useState(false)
  useEffect(()=>{ setPreview(null); setError(""); if(!url.trim()) return; const timer=setTimeout(async()=>{ setChecking(true); try { const r=await fetcher(`/api/soundcloud/admin/resolve?url=${encodeURIComponent(url.trim())}${expected?`&expected=${expected}`:""}`); const d=await r.json(); if(!r.ok) throw new Error(d.message); setPreview(d) } catch(e){ setError(e instanceof Error?e.message:"Bağlantı doğrulanamadı.") } finally { setChecking(false) } },550); return()=>clearTimeout(timer) },[url,fetcher,expected])
  return {preview,error,checking}
}

export function Admin() {
  const { authenticatedFetch, user } = useAuth()
  const [data,setData]=useState<Data>({artists:[],items:[]}), [message,setMessage]=useState(""), [loading,setLoading]=useState(true)
  const [profileUrl,setProfileUrl]=useState(""), [artistUrl,setArtistUrl]=useState(""), [artistDescription,setArtistDescription]=useState("")
  const [itemUrl,setItemUrl]=useState(""), [scope,setScope]=useState<"lowradio"|"partner">("lowradio"), [artistId,setArtistId]=useState("")
  const [search,setSearch]=useState(""), [searchType,setSearchType]=useState("users"), [results,setResults]=useState<Preview[]>([]), [searchEnabled,setSearchEnabled]=useState(false)
  const stableFetch=useCallback((url:string)=>authenticatedFetch(url),[authenticatedFetch])
  const profilePreview=useUrlPreview(profileUrl,stableFetch,"profile"), artistPreview=useUrlPreview(artistUrl,stableFetch,"profile"), itemPreview=useUrlPreview(itemUrl,stableFetch)
  const load=useCallback(async()=>{ const [d,s]=await Promise.all([authenticatedFetch("/api/soundcloud/admin/data"),authenticatedFetch("/api/soundcloud/admin/status")]); if(d.ok){const body=await d.json();setData(body);setProfileUrl(body.settings?.lowradio_tracks_url||DEFAULT_LOWRADIO_TRACKS_URL)} if(s.ok)setSearchEnabled((await s.json()).searchEnabled);setLoading(false) },[authenticatedFetch])
  useEffect(()=>{load()},[load])
  const send=async(url:string,method:string,body?:unknown)=>{setMessage("");const r=await authenticatedFetch(url,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"İşlem başarısız.");return d}
  const saveProfile=async()=>{if(!profilePreview.preview)return;try{await send("/api/soundcloud/admin/settings","PUT",{profileUrl:profilePreview.preview.providerUrl||profilePreview.preview.url,tracksUrl:profileUrl.trim(),profileName:profilePreview.preview.authorName,artworkUrl:profilePreview.preview.artworkUrl});setMessage("LOWRadio track kaynağı kaydedildi.");load()}catch(e){setMessage((e as Error).message)}}
  const addArtist=async()=>{if(!artistPreview.preview)return;try{await send("/api/soundcloud/admin/artists","POST",{profileUrl:artistPreview.preview.url,name:artistPreview.preview.authorName||artistPreview.preview.title,artworkUrl:artistPreview.preview.artworkUrl,description:artistDescription});setArtistUrl("");setArtistDescription("");setMessage("Sanatçı eklendi.");load()}catch(e){setMessage((e as Error).message)}}
  const addItem=async()=>{if(!itemPreview.preview)return;if(scope==="partner"&&!artistId){setMessage("Partner içeriği için sanatçı seçin.");return}try{const isPlaylist=itemUrl.includes("/sets/");await send("/api/soundcloud/admin/items","POST",{scope,artistId:artistId?Number(artistId):null,kind:isPlaylist?"playlist":"track",url:itemPreview.preview.url,title:itemPreview.preview.title,authorName:itemPreview.preview.authorName,artworkUrl:itemPreview.preview.artworkUrl});setItemUrl("");setMessage("İçerik eklendi.");load()}catch(e){setMessage((e as Error).message)}}
  const runSearch=async()=>{if(!search.trim())return;try{const r=await authenticatedFetch(`/api/soundcloud/admin/search?type=${searchType}&q=${encodeURIComponent(search)}`);const d=await r.json();if(!r.ok)throw new Error(d.message);setResults(d.map((x:any)=>({url:x.url,title:x.name,authorName:x.authorName||x.name,artworkUrl:x.artworkUrl}))) }catch(e){setMessage((e as Error).message)}}
  const sortedItems=useMemo(()=>[...data.items].sort((a,b)=>a.sort_order-b.sort_order),[data.items])
  if(loading)return <div className="admin-route-state">Panel yükleniyor…</div>
  return <section className="soundcloud-admin"><header><div><span>ADMIN / 04</span><h1>SoundCloud Yönetimi</h1><p>{user?.email}</p></div><a href="/dj-sets" target="_blank">DJ SETS'İ GÖR <ExternalLink/></a></header>{message&&<div className="admin-message">{message}</div>}
    <div className="admin-grid">
      <section className="admin-panel"><span className="admin-panel-index">01 / KAYNAK</span><h2>LOWRadio Track Kaynağı</h2><p>Sol sütunda otomatik gösterilecek SoundCloud profilinin Tracks bağlantısını belirler.</p><input value={profileUrl} onChange={e=>setProfileUrl(e.target.value)} placeholder={DEFAULT_LOWRADIO_TRACKS_URL}/>{profilePreview.checking&&<small>Bağlantı kontrol ediliyor…</small>}{profilePreview.error&&<small className="admin-error">{profilePreview.error}</small>}{profilePreview.preview&&<PreviewCard data={profilePreview.preview}/>}<button disabled={!profilePreview.preview} onClick={saveProfile}>TRACK KAYNAĞINI KAYDET</button></section>
      <section className="admin-panel"><span className="admin-panel-index">02 / SANATÇI</span><h2>Partner Sanatçı</h2><p>Geçerli profil bağlantısı fotoğraflı kart olarak doğrulanır.</p><input value={artistUrl} onChange={e=>setArtistUrl(e.target.value)} placeholder="SoundCloud profil URL’si"/>{artistPreview.checking&&<small>Profil kontrol ediliyor…</small>}{artistPreview.error&&<small className="admin-error">{artistPreview.error}</small>}{artistPreview.preview&&<PreviewCard data={artistPreview.preview}/>}<textarea value={artistDescription} onChange={e=>setArtistDescription(e.target.value)} placeholder="Kısa açıklama (opsiyonel)"/><button disabled={!artistPreview.preview} onClick={addArtist}>SANATÇIYI EKLE</button></section>
      <section className="admin-panel admin-panel-wide"><span className="admin-panel-index">03 / İÇERİK</span><h2>Parça / DJ Set Ekle</h2><div className="admin-inline"><select value={scope} onChange={e=>setScope(e.target.value as any)}><option value="lowradio">LOWRadio kataloğu</option><option value="partner">Partner sanatçı</option></select>{scope==="partner"&&<select value={artistId} onChange={e=>setArtistId(e.target.value)}><option value="">Sanatçı seçin</option>{data.artists.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select>}</div><input value={itemUrl} onChange={e=>setItemUrl(e.target.value)} placeholder="SoundCloud parça veya DJ Set URL’si"/>{itemPreview.checking&&<small>İçerik kontrol ediliyor…</small>}{itemPreview.error&&<small className="admin-error">{itemPreview.error}</small>}{itemPreview.preview&&<PreviewCard data={itemPreview.preview}/>}<button disabled={!itemPreview.preview} onClick={addItem}>İÇERİĞİ EKLE</button></section>
      {searchEnabled&&<section className="admin-panel admin-panel-wide"><span className="admin-panel-index">04 / ARAMA</span><h2>SoundCloud’da Ara</h2><div className="admin-search"><select value={searchType} onChange={e=>setSearchType(e.target.value)}><option value="users">Sanatçı</option><option value="tracks">Parça</option><option value="playlists">DJ Set</option></select><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&runSearch()} placeholder="Arama…"/><button onClick={runSearch}><Search/> ARA</button></div><div className="admin-results">{results.map(r=><button key={r.url} onClick={()=>searchType==="users"?setArtistUrl(r.url):setItemUrl(r.url)}><PreviewCard data={r}/></button>)}</div></section>}
      <section className="admin-panel admin-panel-wide"><span className="admin-panel-index">05 / YAYIN</span><h2>Yayınlanan İçerikler</h2><div className="admin-content-list">{sortedItems.map(item=><div key={item.id}>{item.artwork_url?<img src={item.artwork_url} alt=""/>:<span>SC</span>}<div><small>{item.scope} / {item.kind}</small><strong>{item.title}</strong></div><label><input type="checkbox" checked={item.active} onChange={async e=>{await send(`/api/soundcloud/admin/items/${item.id}`,"PATCH",{active:e.target.checked});load()}}/> AKTİF</label><button aria-label="Sil" onClick={async()=>{await send(`/api/soundcloud/admin/items/${item.id}`,"DELETE");load()}}><Trash2/></button></div>)}</div></section>
    </div>
  </section>
}
